name: Deploy widget (auto version + purge CDN)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compute VERSION and SHA
        id: meta
        run: |
          echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "version=$(date -u +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Generate version.js
        run: |
          cat > version.js <<'EOF'
// 자동생성 파일: GitHub Actions가 커밋마다 갱신합니다.
window.__WIDGET_MANIFEST__ = {
  version: "${{ steps.meta.outputs.version }}",
  url: "https://cdn.jsdelivr.net/gh/drvalue/drvalue-chat-service@${{ steps.meta.outputs.sha }}/widget.js"
};
EOF

      - name: Commit version.js with [skip ci]
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add version.js
          # 변경이 있어야만 커밋
          if ! git diff --cached --quiet; then
            git commit -m "chore: update version.js to ${{ steps.meta.outputs.version }} [skip ci]"
            git push origin main
          else
            echo "No changes in version.js; skip commit."
          fi

      - name: Purge jsDelivr CDN caches
        run: |
          BASE="https://purge.jsdelivr.net/gh/drvalue/drvalue-chat-service@main"
          curl -sS "${BASE}" || true
          curl -sS "${BASE}/loader.js" || true
          curl -sS "${BASE}/version.js" || true
          curl -sS "${BASE}/widget.js" || true
          # SHA 고정 URL도 미리 퍼지(보수적)
          SHA="${{ steps.meta.outputs.sha }}"
          curl -sS "https://purge.jsdelivr.net/gh/drvalue/drvalue-chat-service@${SHA}/widget.js" || true
